import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ChangeEvent, useState } from "react";
import Spinner from "../components/Spinner";
import { trpc } from "../utils/trpc";
import { HiOutlineTrash } from "react-icons/hi";
import { BsPencilSquare } from "react-icons/bs";

interface NoteDataProp {
  title: string;
  description: string;
}

const Home: NextPage = () => {
  const addNote = trpc.notes.newNote.useMutation();
  const { data: allNotes, isLoading } = trpc.notes.getAllNotes.useQuery();

  const [showForm, setShowForm] = useState(false);
  const [noteData, setNoteData] = useState({} as NoteDataProp);

  const handleTitleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const data = { ...noteData, title: e.target.value };
    setNoteData(data);
  };

  const handleDescChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    const data = { ...noteData, description: e.target.value };
    setNoteData(data);
  };

  const handleSubmit = () => {
    addNote.mutate(noteData);

    setNoteData({
      title: "",
      description: "",
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*              */}
      <main className="flex min-h-screen w-full flex-col  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex w-full  items-center justify-around p-6 text-white">
          {/*   Title   */}
          <h1 className="text-4xl font-bold">Notes</h1>
          <button
            onClick={() => setShowForm((e) => !e)}
            className=" bg-blue-700 px-6 py-2"
          >
            New Note
          </button>
        </div>

        {/*  New Note  Form    */}

        {showForm && (
          <div className="mx-auto flex w-11/12 flex-col gap-y-4  border-2 border-black bg-white/90 p-3 text-center text-white md:w-8/12 lg:w-5/12">
            <h1 className="my-2 text-2xl font-semibold text-black">New Note</h1>
            {/*  Title    */}
            <input
              type="text"
              value={noteData.title}
              onChange={(e) => handleTitleChange(e)}
              placeholder="Title"
              className=" bg-violet-800 p-2 outline-0"
            />
            {/*   Desc   */}
            <textarea
              value={noteData.description}
              onChange={(e) => handleDescChange(e)}
              placeholder="Description"
              className=" bg-violet-800 p-2 outline-0"
            />
            {/*   Add   */}
            <button
              onClick={handleSubmit}
              className="my-2 w-full  bg-blue-700 py-2"
            >
              Add Note
            </button>
          </div>
        )}
        {/*      End New Form            */}

        {/*      Notes  */}
        <div className="mx-auto mt-10 grid w-max grid-cols-3 gap-6">
          {isLoading ? (
            <div>
              <Spinner />
            </div>
          ) : (
            allNotes?.map((data, i) => (
              <Link href={`/notes/${data.id}`}>
                <div
                  className="flex items-center justify-between gap-y-2 gap-x-2 border-8 border-blue-700 bg-white px-6 py-3 shadow-xl transition-all hover:bg-blue-700"
                  key={i}
                >
                  {/*   title   */}
                  <h1 className=" text-2xl font-semibold text-purple-800">
                    {data.title}
                  </h1>
                  {/*   del and edit   */}
                  <div className="flex flex-col gap-y-4 text-2xl">
                    <button className="text-red-600 ">
                      <HiOutlineTrash />
                    </button>

                    <Link href={`/edit/${data.id}`}>
                      <button className="text-emerald-700">
                        <BsPencilSquare />
                      </button>
                    </Link>
                  </div>
                </div>
              </Link>
            ))
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
