import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { ChangeEvent, useState } from "react";
import { trpc } from "../utils/trpc";

interface NoteDataProp {
  title: string;
  description: string;
}

const Home: NextPage = () => {
  // const data = trpc.test.test.useQuery({ msg: "Hehehe" });

  const addNote = trpc.notes.newNote.useMutation();

  const [showForm, setShowForm] = useState(false);
  const [noteData, setNoteData] = useState({} as NoteDataProp);

  const handleTitleChange = (e: ChangeEvent<HTMLInputElement>) => {
    const data = { ...noteData, title: e.target.value };
    setNoteData(data);
  };

  const handleDescChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
    const data = { ...noteData, description: e.target.value };
    setNoteData(data);
  };

  const handleSubmit = () => {
    addNote.mutate(noteData);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*              */}
      <main className="flex min-h-screen w-full flex-col  bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex w-full  items-center justify-around p-6 text-white">
          {/*   Title   */}
          <h1 className="text-4xl font-bold">Notes</h1>
          <button
            onClick={() => setShowForm((e) => !e)}
            className=" bg-blue-700 px-6 py-2"
          >
            New Note
          </button>
        </div>
        {/*    Form    */}
        {showForm && (
          <div className="mx-auto flex w-11/12 flex-col gap-y-4  border-2 border-black bg-white/90 p-3 text-center text-white md:w-8/12 lg:w-5/12">
            <h1 className="my-2 text-2xl font-semibold text-black">New Note</h1>
            {/*  Title    */}
            <input
              type="text"
              value={noteData.title}
              onChange={(e) => handleTitleChange(e)}
              placeholder="Title"
              className=" bg-violet-800 p-2 outline-0"
            />
            {/*   Desc   */}
            <textarea
              value={noteData.description}
              onChange={(e) => handleDescChange(e)}
              placeholder="Title"
              className=" bg-violet-800 p-2 outline-0"
            />
            {/*   Add   */}
            <button
              onClick={handleSubmit}
              className="my-2 w-full  bg-blue-700 py-2"
            >
              Add Note
            </button>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
